version: '3'
services:
  postgresdb:
    image: postgres:16.3
  guestsapp:
    image: 1.0.0
  frontend:
    image: nginx:1.13
    volumes:
      - ./frontend/:/usr/share/nginx/html/
      ports:
        - 80:80